- name: Install required libraries for brave
  apt:
    pkg:
    - curl
    - apt-transport-https
  become: true
  tags: &brave_tags [ 'install', 'brave' ]
- name: brave archive-keyring.gpg download
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  become: true
  tags: *brave_tags
- name: brave repo setting
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
  become: true
  tags: *brave_tags
- name: brave apt installation
  apt:
    update_cache: yes
    name: brave-browser
  become: true
  tags: *brave_tags
