- name: Add tap for fonts
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
  tags: &core_tags [ 'install', 'core' ]
- name: Install System Packages
  community.general.homebrew:
    name:
    - git
    - git-lfs
    - wget
    - httpie
    - jq
    - tmux
    - neovim
    - htop
    - neofetch
    - tldr
    - ffmpeg
    - imagemagick
    - yt-dlp
    state: present
  tags: *core_tags
- name: Install Casks
  community.general.homebrew_cask:
    name:
    - iterm2
    - mpv
    - font-caskaydia-cove-nerd-font
    state: present
  tags: *core_tags
