- name: Install System Packages
  community.general.homebrew:
    name:
    - git
    - git-lfs
    - wget
    - httpie
    - jq
    - tmux
    - neovim
    - htop
    - neofetch
    - tldr
    - mpv
    - ffmpeg
    - imagemagick
    - yt-dlp
    state: present
  tags: &core_tags [ 'install', 'core' ]
- name: Install Casks
  community.general.homebrew_cask:
    name:
    - iterm2
    - visual-studio-code
    state: present
  tags: *core_tags
