- name: Install n node version manager
  community.general.homebrew:
    name:
    - n
    state: present
  tags: &node_tags [ 'install', 'node' ]
- name: Install latest node lts version
  shell: n lts
  become: true
  tags: *node_tags
- name: Install yarn
  shell: corepack enable
  tags: *node_tags
  become: true
- name: Install typescript
  community.general.npm:
    name: typescript
    global: yes
    state: present
  become: true
  tags: *node_tags
- name: Install typescript language server
  community.general.npm:
    name: typescript-language-server
    global: yes
    state: present
  become: true
  tags: *node_tags
