- name: Make vim-plug directory
  ansible.builtin.file:
    path: ~/.local/share/nvim/site/autoload/
    state: directory
    mode: '0755'
  tags: &vim_tags [ 'install', 'vim' ]
- name: Download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
    mode: '0755'
  tags: *vim_tags
- name: Install Telescope Dependencies
  community.general.homebrew:
    name:
    - fzf
    - ripgrep
    - fd
  tags: *vim_tags
