- name: Install required libraries for 1password
  apt:
    pkg:
    - curl
    - apt-transport-https
  become: true
  tags: &pass_tags [ 'install', 'pass' ]
- name: 1password archive-keyring.gpg download
  get_url:
    url: https://downloads.1password.com/linux/keys/1password.asc
    dest: /tmp/1password.asc
  tags: *pass_tags
- name: 1password archive-keyring.gpg dearmor and add to keyrings
  shell: gpg -o /usr/share/keyrings/1password-archive-keyring.gpg --dearmor /tmp/1password.asc
  become: true
  tags: *pass_tags
- name: 1password repo setting
  shell: echo "deb [signed-by=/usr/share/keyrings/1password-archive-keyring.gpg arch=amd64] https://downloads.1password.com/linux/debian/amd64 stable main" | tee /etc/apt/sources.list.d/1password.list
  become: true
  tags: *pass_tags
- name: Make debsig policy directory
  ansible.builtin.file:
    path: /etc/debsig/policies/AC2D62742012EA22/
    state: directory
  become: true
  tags: *pass_tags
- name: 1password debsig policy download
  get_url:
    url: https://downloads.1password.com/linux/debian/debsig/1password.pol
    dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
  become: true
  tags: *pass_tags
- name: Make debsig keyrings directory
  ansible.builtin.file:
    path: /usr/share/debsig/keyrings/AC2D62742012EA22
    state: directory
  become: true
  tags: *pass_tags
- name: 1password debsig keyring download
  get_url:
    url: https://downloads.1password.com/linux/keys/1password.asc
    dest: /tmp/pass-key.asc
  tags: *pass_tags
- name: 1password keyring.gpg dearmor and add to debsig keyrings
  shell: gpg -o /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg --dearmor /tmp/pass-key.asc
  become: true
  tags: *pass_tags
- name: pass apt installation
  apt:
    update_cache: yes
    name: 1password
  become: true
  tags: *pass_tags
