- name: Install required libraries for spotify
  apt:
    pkg:
    - curl
    - apt-transport-https
  become: true
  tags: &spotify_tags [ 'install', 'spotify' ]
- name: spotify archive-keyring.gpg download
  get_url:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    dest: /tmp/spotify-archive-keyring.gpg
  tags: *spotify_tags
- name: spotify archive-keyring.gpg dearmor and add to keyrings
  shell: gpg -o /usr/share/keyrings/spotify-archive-keyring.gpg --dearmor /tmp/spotify-archive-keyring.gpg
  become: true
  tags: *spotify_tags
- name: spotify repo setting
  shell: echo "deb [signed-by=/usr/share/keyrings/spotify-archive-keyring.gpg arch=amd64] http://repository.spotify.com stable non-free" | tee /etc/apt/sources.list.d/spotify.list
  become: true
  tags: *spotify_tags
- name: spotify apt installation
  apt:
    update_cache: yes
    name: spotify-client
  become: true
  tags: *spotify_tags
