- hosts: localhost
  vars:
    python_version: 3.10.6
  pre_tasks:
  - name: Update Homebrew
    community.general.homebrew:
      update_homebrew: yes
    tags:
      - install
      - core
      - vim
      - dotfiles
      - python
  tasks:
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/nvim-setup.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/python-setup.yml
