- hosts: localhost
  pre_tasks:
  - name: Update Homebrew
    community.general.homebrew:
      update_homebrew: yes
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/core-setup.yml
